# Generated by Django 5.1.2 on 2024-10-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('current_cohort', models.CharField(max_length=10)),
                ('current_actionable_bucket', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('clinical_intervention_required', models.BooleanField(default=False)),
                ('quotation_phase_required', models.BooleanField(default=False)),
                ('patient_ready', models.BooleanField(default=False)),
                ('days_since_last_contact', models.IntegerField(default=0)),
            ],
        ),
    ]
