# Generated by Django 5.1.2 on 2024-10-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_quotation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lead_management_active',
            field=models.BooleanField(default=True),
        ),
    ]
